server:
  port: 8090
 
spring:
  datasource:
    url: jdbc:mysql://192.168.31.197:3306/cauchy_note?serverTimezone=GMT
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#showSql
logging:
  level:
    com:
      example:
        mapper : debug