server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://192.168.31.197:3306/cauchy_note_test?serverTimezone=GMT
    username: root
    password: JLLwcl123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    port: 6379
    host: 192.168.31.197
    database: 0
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 3000
    password:
logging:
  file:
  level: {
           root:warn ,
           org.springframework.web:debug
           org.springframework.security:debug
  }

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
